[package]
name = "circuit_playground_express"
version = "0.7.0"
authors = ["Paul Sajna <paulsajna@gmail.com>"]
description = "Board Support crate for the Adafruit Circuit Playground Express"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
documentation = "https://atsamd-rs.github.io/atsamd/atsamd21g18a/circuit_playground_express/"

[dependencies]
cortex-m = "~0.6"
embedded-hal = "~0.2.3"
nb = "~0.1"

[dependencies.atsamd-hal]
path = "../../hal"
version = "~0.9"
default-features = false

[dev-dependencies]
panic-halt = "~0.2"
cortex-m-rt = "~0.6.12"

[features]
# ask the HAL to enable atsamd21g18a support
default = ["rt", "atsamd-hal/samd21g18a"]
rt = ["atsamd-hal/samd21g18a-rt"]
unproven = ["atsamd-hal/unproven"]
use_semihosting = []
