[package]
name = "pfza_proto1"
version = "0.5.0"
authors = ["Michael van Niekerk <mvniekerk@gmail.com>"]
description = "Board Support crate for the PathfinderZA Proto1"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
edition = "2018"

[dependencies]
cortex-m = "0.6"
embedded-hal = "0.2.3"
nb = "0.1"

[dependencies.cortex-m-rt]
version = "0.6.12"
optional = true

[dependencies.atsamd-hal]
version = "0.13"
default-features = false

[dev-dependencies]
panic-halt = "0.2"
panic-semihosting = "0.5"
cortex-m-semihosting = "0.3"

[features]
# ask the HAL to enable atsame54p support
default = ["rt", "atsamd-hal/same54p", "atsamd-hal/same54"]
rt = ["cortex-m-rt", "atsamd-hal/same54p-rt"]
unproven = ["atsamd-hal/unproven"]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = true

[profile.release]
lto = true
opt-level = "s"

# for cargo flash
[package.metadata]
chip = "ATSAME54P20A"

[package.metadata.atsamd.bsp]
tier = 2
build_command = "cargo build --examples --features=unproven"
