[package]
name = "sodaq_sara_aff"
version = "0.9.0"
authors = ["Stefan de Lange <langestefan@msn.com>"]
description = "Board Support crate for the Sodaq SARA AFF"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
edition = "2021"

[dependencies.panic-semihosting]
version = "0.6"
optional = true

[dependencies.cortex-m-rt]
version = "0.7"
optional = true

[dependencies.atsamd-hal]
version = "0.14"
default-features = false

[dev-dependencies]
panic-halt = "0.2"

[features]
# ask the HAL to enable atsamd21j support
default = ["rt", "atsamd-hal/samd21j"]
rt = ["cortex-m-rt", "atsamd-hal/samd21j-rt"]
unproven = ["atsamd-hal/unproven"]
use_semihosting = ["panic-semihosting"]

# for cargo flash
[package.metadata]
chip = "ATSAMD21J18A"
