[package]
name = "pygamer"
version = "0.4.0"
authors = [
    "Paul Sajna <sajattack@gmail.com>",
    "Wez Furlong <wez@wezfurlong.org>"
]
description = "Board Support crate for the Adafruit PyGamer"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
documentation = "https://atsamd-rs.github.io/atsamd/atsamd51j19a/pygamer/"
edition = "2018"

[dependencies]
cortex-m = "~0.6"
embedded-hal = "~0.2.3"
nb = "~0.1"
st7735-lcd = "0.7"

[dependencies.cortex-m-rt]
version = "~0.6.12"
optional = true

[dependencies.atsamd-hal]
path = "../../hal"
version = "~0.8"
default-features = false

[dependencies.micromath]
version = "0.5.1"
optional = true

[dependencies.embedded-sdmmc]
version = "0.2.1"
optional = true

[dependencies.ws2812-timer-delay]
version = "~0.3"

[dev-dependencies]
panic-halt = "~0.2"
embedded-graphics = "0.6.0"
smart-leds = "0.3"
ws2812-spi = "0.2.0"
lis3dh = "0.1.0"
cortex-m-rtic = "~0.5.1"

[dependencies.usb-device]
version = "~0.2"
optional = true

[dependencies.usbd-serial]
version = "~0.1"
optional = true

[features]
# ask the HAL to enable atsamd51j20a support
default = ["rt", "atsamd-hal/samd51j19a", "atsamd-hal/samd51", "unproven"]
rt = ["cortex-m-rt", "atsamd-hal/samd51j19a-rt"]
unproven = ["atsamd-hal/unproven"]
usb = ["atsamd-hal/usb", "usb-device", "usbd-serial"]
sd-card = ["embedded-sdmmc"]
math = ["micromath"]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"

[[example]]
name = "usb_serial"
required-features = ["usb"]

[[example]]
name = "usb_poll"
required-features = ["usb"]

[[example]]
name = "sd_card"
required-features = ["sd-card"]

[[example]]
name = "neopixel_easing"
required-features = [ "math"]
