[package]
name = "trellis_m4"
version = "0.6.0"
authors = [
    "Tony Arcieri <bascule@gmail.com>",
    "Paul Sajna <sajattack@gmail.com>",
    "Wez Furlong <wez@wezfurlong.org>"
]
description = "Board Support crate for the Adafruit NeoTrellis M4 Express"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
documentation = "https://atsamd-rs.github.io/atsamd/atsamd51g19a/trellis_m4/"

[dependencies]
cortex-m = "~0.6"
embedded-hal = "~0.2.3"
nb = "~0.1"

[dependencies.cortex-m-rt]
version = "~0.6.12"
optional = true

[dependencies.adxl343]
version = "~0.4"
optional = true

[dependencies.atsamd-hal]
path = "../../hal"
version = "~0.9"
default-features = false

[dependencies.keypad]
version = "~0.1"
optional = true

[dev-dependencies]
panic-halt = "~0.2"
panic-semihosting = "~0.5"
cortex-m-semihosting = "~0.3"
cortex-m-rtic = "~0.5.1"
panic_rtt = "~0.2"
smart-leds = "0.3"

[dev-dependencies.ws2812-timer-delay]
version = "~0.3"

[features]
# ask the HAL to enable atsamd51g19a support
default = ["rt", "atsamd-hal/samd51g19a", "atsamd-hal/samd51"]
rt = ["cortex-m-rt", "atsamd-hal/samd51g19a-rt"]
unproven = ["atsamd-hal/unproven"]
keypad-unproven = ["keypad", "unproven"]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"

[[example]]
name = "neopixel_accel"
required-features = ["adxl343"]

[[example]]
name = "neopixel_blink"

[[example]]
name = "neopixel_orientation"
required-features = ["adxl343"]

[[example]]
name = "neopixel_rainbow"

[[example]]
name = "neopixel_keypad"
required-features = ["keypad-unproven"]

[package.metadata.docs.rs]
features = ["adxl343", "keypad-unproven"]
