[package]
name = "qt_py_m0"
version = "0.10.0"
authors = ["Garret Kelly <gkelly@gkel.ly>"]
description = "Board Support crate for the Adafruit QT Py"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
edition = "2018"

[dependencies]
cortex-m = "0.6"
embedded-hal = "0.2.3"
nb = "0.1"
cortex-m-rt = { version = "0.6.12", optional = true }
usb-device = { version = "0.2", optional = true }
usbd-serial = { version = "0.1", optional = true }

[dependencies.atsamd-hal]
version = "0.13"
default-features = false

[dev-dependencies]
panic-halt = "0.2"
smart-leds = "0.3"
ws2812-timer-delay = { version = "0.3", features = ["slow"] }

[features]
default = ["rt", "atsamd-hal/samd21e"]
rt = ["cortex-m-rt", "atsamd-hal/samd21e-rt"]
unproven = ["atsamd-hal/unproven"]
use_semihosting = []
usb = ["atsamd-hal/usb", "usb-device", "usbd-serial"]

[package.metadata.atsamd.bsp]
tier = 2
build_command = "cargo build --examples --features=unproven,usb"
