[package]
name = "qt_py_m0"
version = "0.10.1"
authors = ["Garret Kelly <gkelly@gkel.ly>"]
description = "Board Support crate for the Adafruit QT Py"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
edition = "2024"

[dependencies.cortex-m]
features = ["critical-section-single-core"]
version = "0.7"

[dependencies.cortex-m-rt]
version = "0.7"
optional = true

[dependencies.usb-device]
version = "0.3.2"
optional = true

[dependencies.atsamd-hal]
version = "0.23"
default-features = false

[dev-dependencies]
usbd-serial = "0.2"
panic-halt = "0.2"
smart-leds = "0.3"
ws2812-timer-delay = { version = "0.3", features = ["slow"] }

[features]
default = ["rt", "atsamd-hal/samd21e"]
rt = ["cortex-m-rt", "atsamd-hal/samd21e-rt"]
use_semihosting = []
usb = ["atsamd-hal/usb", "usb-device"]

[[example]]
name = "usb_echo"
required-features = ["usb"]
