[package]
name = "p1am_100"
version = "0.3.0"
authors = ["Quentin Smith <quentin@mit.edu>"]
description = "Board Support crate for the Facts Engineering P1AM-100"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
edition = "2021"

[dependencies.cortex-m-rt]
version = "0.7"
optional = true

[dependencies.atsamd-hal]
version = "0.14"
default-features = false

[dependencies.usb-device]
version = "0.2"
optional = true

[dev-dependencies]
cortex-m = "0.7"
usbd-serial = "0.1"
cortex-m-semihosting = "0.3"
drogue-nom-utils = "0.1"
nom = { version = "5.1", default-features= false }
heapless = "0.7"
cortex-m-rtic = "1.0"
panic-halt = "0.2"
panic-semihosting = "0.5"

[features]
# ask the HAL to enable atsamd21g support
default = ["rt", "atsamd-hal/samd21g"]
rt = ["cortex-m-rt", "atsamd-hal/samd21g-rt"]
unproven = ["atsamd-hal/unproven"]
use_rtt = ["atsamd-hal/use_rtt"]
usb = ["atsamd-hal/usb", "usb-device"]
dma = ["atsamd-hal/dma"]
max-channels = ["dma", "atsamd-hal/max-channels"]
use_semihosting = []

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

[profile.release]
debug = true
lto = true
opt-level = "s"

[[example]]
name = "blinky_basic"

[[example]]
name = "timers"

[[example]]
name = "pwm"
required-features = ["unproven"]

[[example]]
name = "adc"
required-features = ["unproven"]

[[example]]
name = "uart_echo_rtic"
required-features = ["unproven"]

[[example]]
name = "usb_echo"
required-features = ["usb", "unproven"]

[[example]]
name = "usb_echo_rtic"
required-features = ["usb", "unproven"]

[[example]]
name = "sleeping_timer"

[[example]]
name = "sleeping_timer_rtc"

[[example]]
name = "clock"
required-features = ["usb"]
