[package]
name = "itsybitsy_m0"
version = "0.1.0"
authors = ["Ben Bergman <ben@benbergman.ca>"]
description = "Board Support crate for the Adafruit ItsyBitsy M0"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
documentation = "https://atsamd-rs.github.io/atsamd/atsamd21g18a/itsybitsy_m0/"

[dependencies]
cortex-m = "~0.5"
embedded-hal = "~0.2"
nb = "~0.1"

[dependencies.cortex-m-rt]
version = "~0.6"
optional = true

[dependencies.atsamd21-hal]
path = "../../hal"
version = "~0.2"
default-features = false

[dev-dependencies]
panic-abort = "~0.3"
ssd1306 = "~0.2"
embedded-graphics = "^0.4.0"

[features]
# ask the HAL to enable atsamd21g18a support
default = ["rt", "atsamd21-hal/samd21g18a"]
rt = ["cortex-m-rt", "atsamd21-hal/samd21g18a-rt"]
unproven = ["atsamd21-hal/unproven"]
use_semihosting = []
