[package]
name = "pyportal"
version = "0.10.0"
authors = [
    "Shella Stephens <shella@infracoven.io",
    "Paul Sajna <sajattack@gmail.com>",
    "Wez Furlong <wez@wezfurlong.org>"
]
description = "Board Support crate for the Adafruit PyPortal"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
edition = "2021"

[dependencies.cortex-m-rt]
version = "0.7.1"
optional = true

[dependencies.atsamd-hal]
version = "0.15.1"
default-features = false

[dependencies.display-interface-parallel-gpio]
version="0.6.0"
optional=true

[dependencies.ili9341]
version="0.5.0"
optional=true

[dependencies.usb-device]
version = "0.2.8"
optional = true

[dev-dependencies]
panic-halt = "0.2"
panic-semihosting = "0.5"
smart-leds = "~0.3"
usbd-serial = "0.1.1"
cortex-m = "0.7.4"
embedded-graphics = "0.7.1"

[dev-dependencies.ws2812-timer-delay]
version = "~0.3"

[features]
# ask the HAL to enable atsamd51j support
default = ["rt", "atsamd-hal/samd51j", "atsamd-hal/samd51", "unproven"]
unproven = ["atsamd-hal/unproven"]
rt = ["cortex-m-rt", "atsamd-hal/samd51j-rt"]
usb = ["atsamd-hal/usb", "usb-device"]
display = ["display-interface-parallel-gpio", "ili9341"]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = true

[profile.release]
lto = true
opt-level = "s"

# for cargo flash
[package.metadata]
chip = "ATSAMD51J20A"

[[example]]
name = "blinky_basic"

[[example]]
name = "ili9341_240x320"
required-features = ["display"]

[[example]]
name = "neopixel_rainbow"

[[example]]
name = "usb_echo"
required-features = ["usb"]
