[package]
name = "edgebadge"
version = "0.4.0"
authors = [
    "Jacob Rosenthal <@jacobrosenthal>",
]
description = "Board Support crate for the Adafruit EdgeBadge"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/atsamd-rs/atsamd"
readme = "README.md"
documentation = "https://atsamd-rs.github.io/atsamd/atsamd51j19a/edgebadge/"
edition = "2018"

[dependencies]
cortex-m = "~0.6"
embedded-hal = "~0.2.3"
nb = "~0.1"
st7735-lcd = "~0.5"

[dependencies.cortex-m-rt]
version = "~0.6"
optional = true

[dependencies.atsamd-hal]
path = "../../hal"
version = "~0.8"
default-features = false

[dependencies.micromath]
version = "0.5.1"
optional = true

[dependencies.ws2812-timer-delay]
version = "~0.3"
optional = true

[dev-dependencies]
panic-halt = "~0.2"
embedded-graphics = "~0.4"
smart-leds = "0.3"
ws2812-spi = "0.2.0"
lis3dh = "0.1.0"
cortex-m-rtfm = "~0.4"

[dependencies.usb-device]
version = "~0.2"
optional = true

[dependencies.usbd-serial]
version = "~0.1"
optional = true

[features]
# ask the HAL to enable atsamd51j20a support
default = ["rt", "atsamd-hal/samd51j19a", "atsamd-hal/samd51"]
rt = ["cortex-m-rt", "atsamd-hal/samd51j19a-rt"]
unproven = ["atsamd-hal/unproven"]
usb = ["atsamd-hal/usb", "usb-device", "usbd-serial"]
ws2812-timer = ["ws2812-timer-delay"]
math = ["micromath"]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"

[[example]]
name = "usb_serial"
required-features = ["usb", "ws2812-timer"]

[[example]]
name = "usb_poll"
required-features = ["usb"]

[[example]]
name = "neopixel_tilt"
required-features = ["ws2812-timer"]

[[example]]
name = "neopixel_button"
required-features = ["ws2812-timer", "unproven"]

[[example]]
name = "button_rtfm"
required-features = ["unproven"]

[[example]]
name = "neopixel_rainbow_timer"
required-features = ["ws2812-timer"]

[[example]]
name = "neopixel_adc_light"
required-features = [ "ws2812-timer", "unproven"]

[[example]]
name = "neopixel_adc_battery"
required-features = [ "ws2812-timer" ,"unproven"]

[[example]]
name = "neopixel_easing"
required-features = [ "ws2812-timer" ,"unproven", "math"]
